# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.29

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
        - pipe: atlassian/sftp-deploy:0.5.3
          variables:
            USER: u710970666
            PASSWORD: vpceh25en
            SERVER: '194.5.156.43'
            REMOTE_PATH: '/home/u710970666/domains/shubhamschahar.com/public_html'
            LOCAL_PATH: 'build'
            # SSH_KEY: $MY_SSH_KEY
            DEBUG: 'true'